### ISSUE TITLE
[proposal] Adopt noble-crypto set of libraries instead of @stablelib ones

### ISSUE THREAD

**Issue by ukstv** [decentralized-identity/did-jwt#192]
Currently did-jwt uses @stablelib family of crypto libraries. Apparently, noble-crypto family of libraries, like [noble-ed25519](https://github.com/paulmillr/noble-ed25519), are significantly faster. For ed25519, [my rough benchmarking](https://gist.github.com/ukstv/749132d4ad6a800fe2072b1be6822399) showed 4x-10x increase in performance. Maybe did-jwt can replace stablelib with noble-crypto.

Caveat: noble-crypto assumes BigInt is fully supported in JS environment.

**Comment by mirceanis** [comment]
There is an `Ed25519Signer` based on stablelib which can be replaced by one provided by the user (possibly based on noble):

Verification uses this hard-coded method:
https://github.com/decentralized-identity/did-jwt/blob/95ed4688bdaa04137930d186500e67c5e96fed4e/src/VerifierAlgorithm.ts#L124

Perhaps a customization can be made for verification as well, to use a user-provided mapping for the verification methods instead of the hard-coded one.

**Comment by ukstv** [comment]
One thing that comes with the custom verification methods, is the API. Currently the API of `verifyJWS` and `verifyJWT` is synchornous. It seems reasonable to change the API first to asynchronous, considering most of SubtleCrypto and other crypto APIs are asynchronous too.
