### ISSUE TITLE
how to support sm2 algorithm

### ISSUE THREAD

**Issue by mtiger2k** [decentralized-identity/did-jwt#218]
SM2 is needed  in China project.
It seems did-jwt doesn't support it.

JS version is here: https://github.com/JuneAndGreen/sm-crypto.

thanks.

**Comment by mirceanis** [comment]
does sm2 have a spec?

**Comment by mtiger2k** [comment]
You can refer to this article, https://ieeexplore.ieee.org/document/6201878

**Comment by mtiger2k** [comment]
probably it's ECDSA

**Comment by mirceanis** [comment]
The spec you mention seems to be guarded by institutional login credentials, which I don't have.

It's very unlikely that we can add that support to this library as-is, since that is not a dependency we are prepared to carry around.
After #170 is resolved you should be able to create that support yourself and install sm2 only on your deployments.
I can't provide a timeline for that, though.
